server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://127.0.0.1:3306/adc.ms.oauth2server?characterEncoding=utf8
      username: root
      password: risfeng@123!
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://127.0.0.1:3306/adc.ms.oauth2server.slave?characterEncoding=utf8
      username: root
      password: risfeng@123!
      driver-class-name: com.mysql.cj.jdbc.Driver
    mapper-locations: classpath:mapper/**/**.xml
    type-aliases-package: com.adotcode.oauth2server.domain.entity
  messages:
    encoding: utf-8
    base-folder: i18n

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

json:
  date-format: yyyy-MM-dd HH:mm:ss

#mybatis config
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句控制台输出
# 日志配置



